image: node:18-buster

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn-cache/
    - .cache/

before_script:
  - yarn cache clean
  - yarn install --frozen-lockfile

build:
  stage: build
  script:
    - node -v
    - yarn -v
    - |
      set -e
      yarn vue-tsc --noEmit || (echo "vue-tsc failed" && exit 1)
      yarn tsc --noEmit --extendedDiagnostics || (echo "tsc failed" && exit 1)
      yarn vite build --debug || (echo "vite build failed" && exit 1)
  artifacts:
    when: always
    paths:
      - dist/
      - .yarn-cache/
    expire_in: 1 week

test:
  stage: test
  script:
    - yarn global add pm2
    - pm2 start yarn --name "dev" --interpreter bash -- run dev
    - sleep 30 # Wait for the app to start
    - curl -I http://localhost:3000 || (pm2 logs dev && exit 1) # Check if the app is running and output logs if it fails
  after_script:
    - pm2 stop all
    - pm2 delete all
