image: node:18

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - install
  - build

install:
  stage: install
  script:
    - yarn install

build:
  stage: build
  script:
    - yarn build