image: node:18-buster

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: push

stages:
  - install
  - build

install:
  stage: install
  script:
    - yarn install --frozen-lockfile

build:
  stage: build
  script:
    - yarn build --verbose