image: node:18-buster

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn-cache/
    - .cache/

before_script:
  - yarn cache clean
  - yarn install --frozen-lockfile

build:
  stage: build
  script:
    - node -v
    - yarn -v
    - yarn vue-tsc --noEmit || true
    - yarn tsc --noEmit --extendedDiagnostics || true
    - yarn vite build --debug

test:
  stage: test
  script:
    - yarn global add pm2
    - pm2 start --name "dev" --interpreter bash -- bash -c "yarn run dev"
    - sleep 30 # Wait for the app to start
    - curl -I http://localhost:3000 # Check if the app is running
  after_script:
    - pm2 stop all
    - pm2 delete all
