image: node:16

stages:
  - install
  - build

cache:
  paths:
    - node_modules/
    - .vite/

install_dependencies:
  stage: install
  script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npx vue-tsc --noEmit --verbose
    - npm run build
  artifacts:
    paths:
      - dist/
    reports:
      junit: report.xml # Optional: configure if you have test reports