stages:
  - install
  - build

cache:
  paths:
    - node_modules/
    - .yarn/cache/

install:
  stage: install
  image: node:18
  script:
    - yarn install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
      - .yarn/cache/

build:
  stage: build
  image: node:18
  script:
    - yarn build
  artifacts:
    paths:
      - dist/