/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllEvaluations: typeof import('./src/components/AllEvaluations.vue')['default']
    AllProjects: typeof import('./src/components/AllProjects.vue')['default']
    AllUsers: typeof import('./src/components/AllUsers.vue')['default']
    EvaluationDetails: typeof import('./src/components/EvaluationDetails.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProjectDetails: typeof import('./src/components/ProjectDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    UserDetails: typeof import('./src/components/UserDetails.vue')['default']
  }
}
