/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllEvaluations: typeof import('./src/components/AllEvaluations.vue')['default']
    AllProjects: typeof import('./src/components/AllProjects.vue')['default']
    AllUsers: typeof import('./src/components/AllUsers.vue')['default']
    EvaluationCard: typeof import('./src/components/EvaluationCard.vue')['default']
    EvaluationDetails: typeof import('./src/components/EvaluationDetails.vue')['default']
    EvaluationList: typeof import('./src/components/EvaluationList.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectDetail: typeof import('./src/components/ProjectDetail.vue')['default']
    ProjectDetails: typeof import('./src/components/ProjectDetails.vue')['default']
    ProjectForm: typeof import('./src/components/ProjectForm.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    SpecificUser: typeof import('./src/components/SpecificUser.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
  }
}
